#!/bin/bash
c="$(nproc)"
echo "Ilość rdzeni procesora: $c"
d="$(free -g)"
echo "Ilość pamięci w GB: "
echo "$d"
e="$(docker container ls -a)"
f="$(docker ps)"
echo "Kontenery Docker'a dostępne na hoście: $e"
echo "Kontenery Docker'a dostępne na hoście: $f"
